### ISSUE TITLE
Window resizing cuts video frame

### ISSUE THREAD

**Issue by ghjansen** [RestComm/olympus#109]
When using video and the size of the screen is not big enough, part of the video frame is not shown at the bottom. Does Olympus have some minimal window size requirement? The video resolution used is 720p.

<img width="1272" alt="screen shot 2017-04-21 at 9 27 33 pm" src="https://cloud.githubusercontent.com/assets/1459428/25291654/5735dcc4-26a9-11e7-84bd-1b8ee2d779a5.png">

**Comment by ammendonca** [comment]
This was fixed with d78f5c4efaa269c6af0b79f75a577034bbb3b00e.
