### ISSUE TITLE
Add support for Safari WebRTC for IOS 11 and MacOS 10.13 High Sierra

### ISSUE THREAD

**Issue by marca56** [RestComm/olympus#116]
* Safari for MacOS High Sierra 10.13 
* Safari for IOS 11

See, https://telestax.atlassian.net/browse/PI-13
See, https://telestax.zendesk.com/agent/tickets/34780

**Comment by ammendonca** [comment]
Initial work done, missing a fix to ICE candidates gathering, to be completed https://github.com/RestComm/olympus/issues/146
