### ISSUE TITLE
Add "ribbon" under main title bar and change name to "WebRTC Test Client" from "Olympus"

### ISSUE THREAD

**Issue by marca56** [RestComm/olympus#117]
* should also change "Olympus" to "WebRTC Test Client" elsewhere in the UI and in the portal;
* should show the app version as well on the "ribbon" after "BETA"

**Comment by ammendonca** [comment]
Sign in screen
![image](https://user-images.githubusercontent.com/1737954/29981290-18a5eed6-8f45-11e7-984e-e05834970dd4.png)

Main application screen
![image](https://user-images.githubusercontent.com/1737954/29981324-310fe9f4-8f45-11e7-9926-a302579a0e7e.png)
