### ISSUE TITLE
Improve error handling on login when underlying service(s) are unavailable

### ISSUE THREAD

**Issue by marca56** [RestComm/olympus#119]
* When an underlying service is down (*i.e.,* SIP, Connect, etc.), a user should receive an error message to the effect of "Service is temporarily unavailable... please try again later"
* Current situation when underlying service is unavailable is user tries to login and gets no response from the server and is not logged in. Then, they think username or password is wrong and try to change it. When that does not work, they send a support message to reset the username or password or just give up.

**Comment by ammendonca** [comment]
Proposed solution

![image](https://user-images.githubusercontent.com/1737954/27235484-eb1242b2-52b8-11e7-8a88-358433a6718a.png)

**Comment by marca56** [comment]
👍 looks good to me

**Comment by deruelle** [comment]
@ammendonca let's make the message configurable as for on-premise deployment or community, the second part of the message will not make sense.
