### ISSUE TITLE
Add a keyboard shortcut to toggle DTMF keypad

### ISSUE THREAD

**Issue by ammendonca** [RestComm/olympus#123]
Currently, during a call, the keypad (for DTMF) can be used via the keyboard, given that the keypad is open, which requires a mouse click to open.

It should be possible to open/close the keypad without using the mouse, eg, the `.` key can be used to open the keypad and then dial the DTMF using the keyboard, for a full mouse-less interaction.

**Comment by marca56** [comment]
* focus should shift to the keyboard when a contact is selected;
* hardware keyboard entry should be enabled
* toggle to show onscreen keyboard should be just click on the keyboard icon that's there

**Comment by ammendonca** [comment]
@marca56, I'm not sure I understand your points. The idea behind this issue is to simply allow showing / hiding the DTMF keypad using the hardware keyboard, to make the interaction easier for people who are more keyboard users than mouse :)

The general idea is that hitting the `.` key would be equivalent to clicking the toggle keypad icon, as in:

![image](https://user-images.githubusercontent.com/1737954/27444957-02c31696-5770-11e7-8f43-a470823fb87c.png)

The possibility of using the hardware keyboard for pressing the DTMF keys is already in place, but requires the keypad to be visible.

**Comment by marca56** [comment]
OK-- my point is that the hardware keyboard should always be available in that screen
