### ISSUE TITLE
Move all resources to be local

### ISSUE THREAD

**Issue by ammendonca** [RestComm/olympus#124]
Some resources (JS/CSS/Fonts) are being retrieved from remote sites. We should have all resources being served locally in order for the app to fully function in a local environment without access to outside network.

**Comment by marca56** [comment]
do you mean that the first time they are used, the resources should be cached locally for further use?

**Comment by ammendonca** [comment]
No, we should only use resources that are inside the deployed WAR. Currently there are (at least) some CSS and Fonts being retrieved from remote (github, google servers). That won't work properly if installed locally with no access to the internet. Plus those servers can change/disappear and then it won't work any way.

**Comment by marca56** [comment]
understood-- so I agree with the story. Let's use only local resources.
