### ISSUE TITLE
Remove default mockup pictures, replace with personalized

### ISSUE THREAD

**Issue by ammendonca** [RestComm/olympus#125]
Currently we are using the pictures from the mockups for the contacts and most importantly for the chat, where the same picture is used for the logged user and any contacted user messages, which causes confusion.

It should be replaced with custom, and possibly personalized (or random as slack or github does) avatars.

**Comment by marca56** [comment]
random is fine because it's less work and will look better than what we have

**Comment by ammendonca** [comment]
![image](https://user-images.githubusercontent.com/1737954/33951326-978cd6ce-e026-11e7-8d6c-b66df2ab6002.png)
