### ISSUE TITLE
Show photo/contact info if it has no video

### ISSUE THREAD

**Issue by ammendonca** [RestComm/olympus#126]
Currently when an audio call is placed, or the remote party is not sending video, the video area is empty, feeling that something is missing.

The contact photo, with a proper background should be displayed.

**Comment by marca56** [comment]
if no photo, should show an avatar by default

**Comment by ammendonca** [comment]
Yes, that should be covered in https://github.com/RestComm/olympus/issues/125. This is more about the "video area" being empty when on an audio call for instance, as in:

![image](https://user-images.githubusercontent.com/1737954/27442991-b6ad24d2-5769-11e7-8ca6-74350bc46110.png)

It should be more like this (alert, bad mockup :))

![image](https://user-images.githubusercontent.com/1737954/27443300-883599e4-576a-11e7-999a-f667c5cbc7b2.png)

**Comment by marca56** [comment]
agreed--

**Comment by ammendonca** [comment]
Audio-only on call screen

![image](https://user-images.githubusercontent.com/1737954/29975541-a564861e-8f2e-11e7-8fac-aadccd81abd3.png)
