### ISSUE TITLE
Reflect registration state in UI

### ISSUE THREAD

**Issue by jaimecasero** [RestComm/olympus#142]
After login it seems no state on current status of regsitration is available in GUI. Would be great to have an status indicator with different colors depending on the state (whether we receive OPTIONS heaertbeat from server or not...)

**Comment by ammendonca** [comment]
## Online
![image](https://user-images.githubusercontent.com/1737954/33618086-7c6da8d0-d9d9-11e7-85bf-bf7ca80833d1.png)

## Connectivity Issues
![image](https://user-images.githubusercontent.com/1737954/33618111-8da9d40c-d9d9-11e7-81cd-1f657dc63938.png)
