### ISSUE TITLE
Adding contact screen does not have cancel button

### ISSUE THREAD

**Issue by jaimecasero** [RestComm/olympus#143]
user really need to add something, so if you hit add by mistake you need to add a contact and then delete it... THere is no other way to go back to regular contact list...

**Comment by ammendonca** [comment]
It is possible to go back to the contact list by clicking the `+` sign, used to show the Add Contact screen, again. I agree this is not the best UX, something to review. Thanks!

**Comment by ddhuy** [comment]
I also met the same problem when adding contact.
