### ISSUE TITLE
Olympus-Web takes long time to establish calls

### ISSUE THREAD

**Issue by suyashbhatt** [RestComm/olympus#153]
Calling a restcomm client from olympus-web takes roughly about 45 seconds. But calling olympus-web client from olympus-android is fast, almost instantaneous.

Chrome console logs: https://gist.github.com/suyashbhatt/29a1c6984b0144c54ca6a8db59b9af7b

**Comment by gsaslis** [comment]
thanks @suyashbhatt !

@ammendonca / @otsakir could you please take a look at this one?

**Comment by suyashbhatt** [comment]
@ammendonca commented on issue I created in Restcomm Connect repo, i closed issue there and reposted it here.
Here is what her response was:
```
This seems like a known issue, it happens when there are network interfaces which have an IP address but have no internet connectivity, so the ICE candidate gathering takes more time, as it waits for that interface to timeout. This typically occurs with VM network adapters (probably that 10.0.0.90 interface?)

The proper solution would be to implement trickle ICE so that it starts using the candidates as they are gathered instead of waiting for the whole thing to complete
```

10.0.0.90 interface was the interface I was making call from. And it happens even if I use different device like browser in cellphone

**Comment by gsaslis** [comment]
@ammendonca this looks like we're still missing some more data from @suyashbhatt ?

**Comment by suyashbhatt** [comment]
Sorry I forgot to update the issue. I have been doing lot of stuffs in my DigitalOcean droplet and few days ago I decided to use new droplet for RC and this issue seems to be fixed. I will give an update later if issue is persistent after my other changes and it might help me to find what caused the issue

**Comment by gsaslis** [comment]
Ok thanks @suyashbhatt

**Comment by gsaslis** [comment]
I will close this for now – please feel free to reopen if you find that the problem persists
