### ISSUE TITLE
No Answer/Rejected! when dialing +1234

### ISSUE THREAD

**Issue by arslan70** [RestComm/olympus#20]
After clicking the call button to +1234, the page holds on for a while and last line of console shows 

**"PrivateJainSipClientConnector:processDialogTerminated()"**
then after a few seconds there is a dialog which shows "No Answer/Rejected! Your call to +1234 was not answered."

Server log: http://pastebin.com/BUsKHTqN

Olympus console output: http://pastebin.com/wAsvVeVK

**I am able to dial +1234 from linphone and can hear the welcome prompt.**

Using restcomm build: Mobicents-Restcomm-JBoss-AS7-7.5.0.782

**Comment by atsakiridis** [comment]
@arslan70 @deruelle this is a known issue in the Media Server that only occurs with Firefox. We have an open issue with more details at:

https://github.com/RestComm/mediaserver/issues/67

A workaround until a fix is in place that has been working for me is to use Chrome instead. I'm closing this issue for now. If you have the same issue in other browsers as well please reopen.

**Comment by arslan70** [comment]
Hey, thanks for the quick reply. As of now chrome doesn't allow media over insecure sessions. Is there a guide to setup https for restcomm?

**Comment by atsakiridis** [comment]
Right, so you can use the latest Docker image that supports https out of the box:

http://docs.telestax.com/restcomm-docker/

For more generic info on how to install Docker, please check:

https://github.com/RestComm/Restcomm-Docker
