### ISSUE TITLE
Sometimes media isn't heard when Olympus calls 1234/1235

### ISSUE THREAD

**Issue by atsakiridis** [RestComm/olympus#21]
Unfortunately, I've been doing numerous tests and I haven't been able to find a root cause. The 'pattern' I see is this:
- Start docker (on amazon, **ubuntu** ami)
- Test Olympus from my PC media doesn't work (for 1234, 1235)
- After some attempts, something triggers it to start working (I know veery strange)
- From then on everything is fine
- I managed to get logs and pcap for both scenarios (good and bad) and compare them but haven't managed to find anything
- This seems to be happening only to me; @otsakir tested it successfully 100% of the times
- If I stop/remove the container and then run it again I get the same issue all over

Good and bad logs and pcaps:

https://drive.google.com/file/d/0BwfD74mG87iMa2JOSGY2cWo5WUU/view?usp=sharing

**Comment by hrosa** [comment]
Logs and PCAP seem good, only issue I see with "bad" pcap is that RTP packets coming from Media Server have their SSRC=0x0 which is wrong.
Related issue https://github.com/RestComm/mediaserver/issues/79

**Comment by atsakiridis** [comment]
This was a Media Server issue after all, handled with:

https://github.com/RestComm/mediaserver/issues/79
