### ISSUE TITLE
Considerations about Organizations

### ISSUE THREAD

**Issue by ghjansen** [RestComm/olympus#39]
With the last efforts introducing the concept of Organizations in RestComm (RestComm/RestComm-Connect#748) its important to check if WebRTC will require some special compatibility adjustments to run properly under this new perspective.

Performing some tests with Olympus, it was noticed that a Client is able to login (register) but when dialing to a number (associated to an application) the call seems not stablished as it usually happens.

It is possible to determine the reason of this problem, based in the console logs and the server logs attached to this issue? I suspect about HTTPs configuration, but I'm opening this issues to request some guidance during the tests, just in case. :)

Thanks in advance!
[foobar.restcomm.com-1464718683513.txt](https://github.com/RestComm/olympus/files/291895/foobar.restcomm.com-1464718683513.txt)
[server.txt](https://github.com/RestComm/olympus/files/291898/server.txt)

**Comment by deruelle** [comment]
You didn't setup https, see in the logs of the browser:

The following error occured:  NavigatorUserMediaError {name: "PermissionDeniedError", message: "Only secure origins are allowed (see: https://goo.gl/Y0ZkNV).", constraintName: ""}

**Comment by ghjansen** [comment]
Thanks @deruelle , after configuring HTTPS Olympus worked well.
Here are some things i discovered during the tests with Olympus, that i'll keep investigating to solve:
* When building RestComm from source, the Olympus version packed inside the final release seems older than the one informed in the `build.xml` script;
* Olympus is able to proceed with registration of clients from Organizations different than the one informed at URL.

I will keep this issue open just in case and keep sharing my findings until its done.
Thanks for the support!
