### ISSUE TITLE
Introduce configuration file for Olympus

### ISSUE THREAD

**Issue by atsakiridis** [RestComm/olympus#55]
So that stuff like:
- WS protocol
- Port
- Consider also adding STUN/TURN servers & credentials

Can be configured instead of resorting to changing olympus/src/main/webapp/resources/js/controllers/register.js with scripts.

**Comment by atsakiridis** [comment]
@brainslog I assigned this to you, do you think you can add it in your todo list? 

After discussion with @leftyb and @maria-farooq this is the plan:
- Introduce `$RESTCOMM_HOME/standalone/deployments/olumpus.war/WEB-INF/conf/olympus.xml`where configuration described above with reside and from where Olympus will get it.
- Restcomm configuration scripts will update that .xml based on deployment

@brainslog, please let me know if you see any issues with the suggested logic

**Comment by ammendonca** [comment]
A possible format for the configuration file:

```
<?xml version="1.0" encoding="UTF-8"?>

<olympus>

  <server secure="true">
    <address>could.restcomm.com</address>
    <port>5082</port>
  </server>

  <stun enabled="true">
    <address>stun.l.google.com</address>
    <port>19302</port>
  </stun>

  <turn enabled="true">
    <address>https://service.xirsys.com/ice</address>
    <domain>cloud.restcomm.com</domain>
    <login>MY_USERNAME</login>
    <password>MY_PASSWORD</password>
  </turn>

</olympus>
```

I think it covers most of the configuration we need to have for now. Anything missing ?

Now, regarding the format and location of the configuration file, for consuming in a web application, this is not the best format, JSON would be more appropriate, but if it makes it easier for consuming by internal configuration tools, I can handle it with X2JS framework which will convert this into JSON. If we could go natively with JSON, it'd look something like this:

```
{
  "olympus": {
    "server": {
      "secure": "true",
      "address": "could.restcomm.com",
      "port": "5082"
    },
    "stun": {
      "enabled": "true",
      "address": "stun.l.google.com",
      "port": "19302"
    },
    "turn": {
      "enabled": "true",
      "address": "https://service.xirsys.com/ice",
      "domain": "cloud.restcomm.com",
      "login": "MY_USERNAME",
      "password": "MY_PASSWORD"
    }
  }
}
```

Regarding the location, a file inside `WEB-INF` is not publicly accessible, so the Olympus webapp cannot retrieve it from there. Would `olympus/src/main/webapp/resources/xml/olympus.xml` be a good alternative ?

/cc @atsakiridis @leftyb @maria-farooq

**Comment by atsakiridis** [comment]
@ammendonca a couple of notes on the configuration file contents:
- Why don't we have 'secure' and 'enabled' attributes as children, the way you did for the rest of the settings like address, etc? Am I missing sth? I think it will be more consistent and easier to read from internal tools
- I don't know if you recall, but webrtcomm configures stun and turn in 2 different ways. 
    - The 'automatic configuration url' way by using what you have included in 'turn' parent element above. In that case you don't need to specify separate 'stun' parent element because stun server(s) are returned by the auto-conf url too. 
    - The 'manual' way where you just provide each stun and turn server manually without the auto-conf step and these are directly passed to peer connection.

These two should probably be mutually exclusive to keep things simpler by the way. So for example the following configuration would suffice (now that you have tested Olympus with auto-conf URL for cloud this would be enough):

```
  <server secure="true">
    <address>could.restcomm.com</address>
    <port>5082</port>
  </server>

  <turn enabled="true">
    <address>https://service.xirsys.com/ice</address>
    <domain>cloud.restcomm.com</domain>
    <login>MY_USERNAME</login>
    <password>MY_PASSWORD</password>
  </turn>
```

Since the xirsys will return both STUN and TURN servers (an added benefit is that we use Xirsys for both, which we are paying for and hence get support, etc). 

Also, I would recommend:
- To change 'address' for 'turn' section to 'url' to make it clearer of what is expected there. Actually we could change all addresses to urls and remove the ports because that is what is used internally, if that makes sense to you.
- To change 'turn' into something like 'ice-auto-configuration' in the parent element name since turn would be a bit misleading (since it also returns STUN url).
- To consider being able to configure both cleartext and secure signaling ports in 'server'. Because I think we allow both cleartext and secure access of Olympus, right? Of course with webrtc cleartext is only allowed for localhost nowadays, so we need to think about that as well. Ideas?

Still would be nice to be able to set STUN and TURN manually if needed, like for example:

```
  <stun enabled="true">
    <address>stun.l.google.com</address>
    <port>19302</port>
  </stun>

  <turn enabled="true">
    <address>turn.l.google.com</address>
    <port>19302</port>
    <login>MY_USERNAME</login>
    <password>MY_PASSWORD</password>
  </stun>
```

But then we need to see how combine both auto-conf and manual setting while keeping the 'interface' simple. Another idea could be to just leave auto-conf settings for now, since that is what we will be using for the cloud and revisit later.

What do you think?

Sorry for long response :D

**Comment by atsakiridis** [comment]
Btw, I think we also need @leftyb input from the DevOps side of things. Lefty, can you have a look?

**Comment by ammendonca** [comment]
@atsakiridis, thanks for the long response! ;)

Some answers inline.

> - Why don't we have 'secure' and 'enabled' attributes as children, the way you did for the rest of the settings like address, etc? Am I missing sth? I think it will be more consistent and easier to read from internal tools

Well, there's no hard rule on when to use attributes or elements. In my opinion, those "toggles" which aren't actual _data_ make more sense to be attributes, while the actual configuration more complex data are elements.

>[STUN/TURN] These two should probably be mutually exclusive to keep things simpler by the way. So for example the following configuration would suffice (now that you have tested Olympus with auto-conf URL for cloud this would be enough):

You're right, they aren't likely necessary to have both, but that was the reason I've added the `enabled` attribute, in order to disable what we don't need/want to use. I prefer like that instead of deleting (can always be commented, but..) the ones not needed, because when wanting to add back I always need to find what is the format, etc.

> To change 'address' for 'turn' section to 'url' to make it clearer of what is expected there. 

Agree, was about to but for consistency with 'stun', I left it with address, which is valid anyway.. but we can change.

> To change 'turn' into something like 'ice-auto-configuration' in the parent element name

Agree.

> To consider being able to configure both cleartext and secure signaling ports in 'server'. Because I think we allow both cleartext and secure access of Olympus, right?

I am not sure we support both at the same time, but if so we can find a way to define both.

> Still would be nice to be able to set STUN and TURN manually if needed, like for example: (...) But then we need to see how combine both auto-conf and manual setting while keeping the 'interface' simple.

If we are renaming what we call 'turn' now, we can have the others as well, and whatever comes first will be tried first... eg, if we have the auto-config as first but it is down (or fails), we fallback to next (stun or turn) configuration, and so on... but this can come after we have things better defined.

**Comment by atsakiridis** [comment]
Thanks @ammendonca, please see below for some further answers

On Wed, Jun 14, 2017 at 8:50 PM, Alexandre Mendonça <
notifications@github.com> wrote:

> @atsakiridis <https://github.com/atsakiridis>, thanks for the long
> response! ;)
>
> Some answers inline.
>
>
>    - Why don't we have 'secure' and 'enabled' attributes as children, the
>    way you did for the rest of the settings like address, etc? Am I missing
>    sth? I think it will be more consistent and easier to read from internal
>    tools
>
> Well, there's no hard rule on when to use attributes or elements. In my
> opinion, those "toggles" which aren't actual *data* make more sense to be
> attributes, while the actual configuration more complex data are elements.
>

Makes sense

> [STUN/TURN] These two should probably be mutually exclusive to keep things
> simpler by the way. So for example the following configuration would
> suffice (now that you have tested Olympus with auto-conf URL for cloud this
> would be enough):
>
> You're right, they aren't likely necessary to have both, but that was the
> reason I've added the enabled attribute, in order to disable what we
> don't need/want to use. I prefer like that instead of deleting (can always
> be commented, but..) the ones not needed, because when wanting to add back
> I always need to find what is the format, etc.
>

Sure I just mentioned that in case you don't want to spend the time right
now to make sense of the combinations and come up with configuration 'api'
that will be able to handle all cases


> To change 'address' for 'turn' section to 'url' to make it clearer of what
> is expected there.
>
> Agree, was about to but for consistency with 'stun', I left it with
> address, which is valid anyway.. but we can change.
>
> To change 'turn' into something like 'ice-auto-configuration' in the
> parent element name
>
> Agree.
>
> To consider being able to configure both cleartext and secure signaling
> ports in 'server'. Because I think we allow both cleartext and secure
> access of Olympus, right?
>
> I am not sure we support both at the same time, but if so we can find a
> way to define both.
>
Yeah this is tricky in the sense that I think it's possible to provide
connectors for http/https at the same time, but I wonder if its really
usable. So feel free to leave it at that

> Still would be nice to be able to set STUN and TURN manually if needed,
> like for example: (...) But then we need to see how combine both auto-conf
> and manual setting while keeping the 'interface' simple.
>
> If we are renaming what we call 'turn' now, we can have the others as
> well, and whatever comes first will be tried first... eg, if we have the
> auto-config as first but it is down (or fails), we fallback to next (stun
> or turn) configuration, and so on... but this can come after we have things
> better defined.
>
Sure
