### ISSUE TITLE
message scrolling is appearing only partially

### ISSUE THREAD

**Issue by maria-farooq** [RestComm/olympus#65]
@ipsilantide 
version : olympus 2.X 
https://cloud.restcomm.com/olympus/#/home

we tried to send couple of messages from olympus to a mobile.
each message contained message number, for example first msg was 1, second was 2 and so we sent 13 messages.
In chat window scroll was not appearing for whole chat are instead it was partial which does not seem correct
its difficult thing for me to explain in words lets take a look at screen shots :)

in the image `scroll` we can see scroll is not covering until bottom
in the image `olympus` we can see that we only see 5 from 1 to 5 and rest of the messages are hidden bcz of scroll.

![scroll](https://cloud.githubusercontent.com/assets/17044714/20601453/87aacbce-b27a-11e6-9a85-9d396198963c.png)
![olympus_](https://cloud.githubusercontent.com/assets/17044714/20601935/e9c1d4fe-b27c-11e6-9300-bce40986065a.png)

**Comment by ammendonca** [comment]
Fixed with 994ab9b15e152351f082608982f7d56d64f8e580.
