### ISSUE TITLE
No scrolls on Olympus to view whole UI in a smaller screen

### ISSUE THREAD

**Issue by maria-farooq** [RestComm/olympus#67]
@ipsilantide @brainslog  
there is no scroll in main olympus views
for instance if i open olympus in a smaller browser window, i can not scroll up/down or left/right to view rest of the view
Please close this issue in case its duplicate
thanks.

**Comment by ammendonca** [comment]
Fixed with 81b78800a306465997dd1fe479225925d0f3eeca.
