### ISSUE TITLE
Olympus Web Isn't Responsive When Minimizing Under 50% Width

### ISSUE THREAD

**Issue by desipepova** [RestComm/olympus#69]
Olympus Web responsiveness breaks when minimizing the screen width under 50%. Log in fields aren't aligning properly. In-a-call icons got cluttered. There isn't a button you can hit to show the list of contacts. There is not escape button (for example when you are trying to add a contact there is no way to get back to the home screen unless you finish the process of adding the new contact).

![2](https://cloud.githubusercontent.com/assets/8472735/20631576/fb5c48d4-b33f-11e6-8e12-6bca6d34083d.png)
![2](https://cloud.githubusercontent.com/assets/8472735/20631640/6c5addc0-b340-11e6-9de1-5f21fb2cc111.png)

![1](https://cloud.githubusercontent.com/assets/8472735/20631538/cd1d347e-b33f-11e6-9d0b-b4166f6e0e33.png)
![2](https://cloud.githubusercontent.com/assets/8472735/20631540/cd1f1b86-b33f-11e6-9bd0-da398dad18c1.png)
![5](https://cloud.githubusercontent.com/assets/8472735/20631541/cd213092-b33f-11e6-8171-093a2e490860.png)
![6](https://cloud.githubusercontent.com/assets/8472735/20631539/cd1f222a-b33f-11e6-8e48-5b0503cfc75e.png)

**Comment by deruelle** [comment]
@desipepova can you confirm it's better now (don't forget to force a refresh of olympus with Shift+F5)

**Comment by ammendonca** [comment]
Fixed with 81b78800a306465997dd1fe479225925d0f3eeca.
