### ISSUE TITLE
All Icons will disappear from Olympus while on a call if I switch screens (tabs)

### ISSUE THREAD

**Issue by jjsenay** [RestComm/olympus#72]
When I am on a call,  and I mute myself, and go to another tab, when I come back to the Olympus screen. The screen is blank.  The handset, and the Muted Microphone icons are gone.  THere is noway that I can unmute myself or hangup.  I have to kill teh tab.

**Comment by ammendonca** [comment]
Unable to replicate. Please reopen if it happens again.
