### ISSUE TITLE
Olympus is not sending BYE in some case

### ISSUE THREAD

**Issue by maria-farooq** [RestComm/olympus#82]
@atsakiridis  in latest Olympus (build latest as per 30th December)
While testing it on staging i have been making calls from olympus WEB
And it is observed that In some scenarios Olympus is not sending BYE to restcomm.
Please note that i am properly hanging up by clicking on button.

Here is a sample console log from Chrome:
we can see multiple calls in this log
for all calls proper `INVITE` and `BYE` can be seen except the one which has: 
`(RC-callSID = CA285c526826fb4c19b17a463328b9e7b7 and sip id = 1483183053797)`

for this call we don't see BYE
its not happening with all calls, its very occasional
[telestax.restcomm.com-1483183478811.com-1483183478811.zip](https://github.com/RestComm/olympus/files/679601/telestax.restcomm.com-1483183478811.com-1483183478811.zip)

### Steps to reproduce:
- login on https://telestax.restcomm.com/olympus/#/
- try to make a couple of calls and from hangup them respectively
- we can check from Call API that some(one or more) will still be in progress

**Comment by maria-farooq** [comment]
i tried to reproduce it today and was not able to, is it possible that it could be due to a network issue on my side, although all those 10s of attempts i did back to back, and only one of them failed.

**Comment by atsakiridis** [comment]
Did some digging and it seems that there are 2 separate calls being made towards +1311 from olympus that are apart around only 200ms! This could easily lead to problems later, given that Olympus isn't designed to handle more than one call in parallel. 

But given that the UI doesn't allow for user pressing the call button twice, I wonder if there might be an issue with new olympus code that might allow for such a scenario (i.e. webrtcomm.call() being called twice). 

I tried to follow through the new olympus code at home.js to see how makeCall is called and see if it can be invoked twice but I'm missing something there. @brainslog can you have a look?

**Comment by ammendonca** [comment]
I have tried to reproduce this issue without success. Even trying to programmatically push the call button twice, the second call attempt failed with `2017-21-06 13:02:52.901 ERROR WebRTCommClient:call(): catched exception:WebRTCommClient:call(): call already ongoing`.

Closing, please reopen if you experience it again.
