### ISSUE TITLE
Use of cached credentials to avoid second login

### ISSUE THREAD

**Issue by otsakir** [RestComm/olympus#86]
Olympus can take advantage of the credentials cached by Dashboard in order to avoid asking the user to login twice. 

Check sessionStorage.sid and sessionStorage.auth_token properties.

Relates to https://github.com/RestComm/Restcomm-Connect/issues/1708

**Comment by ammendonca** [comment]
@otsakir I am not sure we can make use of those credentials as the ones used to login for Olympus are the ones from the clients (which can be more than one), while the ones we have for dashboard are for the user itself, right ?

**Comment by otsakir** [comment]
@ammendonca you 're right. I referred to _account_ credentials while Olympus uses _client_ credentials for authentication. On the other hand account credentials is a powerful thing. One can get client credentials by using account credentials to access Clients endpoint. 

I'm not sure what's the plan for Olympus and whether is has to be account-agnostic. In any case, here is how i thought of it:

1. Olympus login form asks user for account sid/token. Here we brake old UX.
2. The (account) credentials entered are authenticated against restcomm.
3. An intermediate state is introduced in terms of UI where the account credentials are accepted but there is no registered client yet. At this point all available clients are retrieved and a list of them is presented to the user to chose one.
4. User picks one, the _client's_ credentials are stored in sessionStorage and things get back to normal i.e. client registers, the typical Olympus screen appears etc.

@ammendonca , i'm not suggesting this since i'm not aware of other complications. For example:

1. Will Client credentials always be part of the GET .../Clients method ?
2. It all has to work in a single tab. Moving from Dashboard to Olympus and maybe RVD.
3. What happens with navigation ? Since the goal is a basic SSO experience, there are also navigation considerations to avoid bad UX. So, the user needs to have a way to switch from Dashboard to Olympus (already in place) and vice versa (not available currently). 
4. Will problems in Olympus resource management affect Dashboard operation. I'm not sure of the internals there.  ? 

It still seems like a (bumpy) way to go.

**Comment by ammendonca** [comment]
![image](https://user-images.githubusercontent.com/1737954/34022259-319add3c-e136-11e7-8865-8219a4e91478.png)
