### ISSUE TITLE
We need a sound as long as the user is waiting the participant to answer

### ISSUE THREAD

**Issue by ipsilantide** [RestComm/olympus#93]
@ipsilantide commented on [Fri Dec 23 2016](https://github.com/RestComm/graphics-design/issues/64)

While the person who makes the call is waiting the other participant to answer we need a sound to play

**Comment by ipsilantide** [comment]
moved here from design repository

**Comment by ammendonca** [comment]
Fixed with e50cc3ea4044284f65734f0af8c7fcb713536e9c.
