### ISSUE TITLE
The main video window need to keep it's size

### ISSUE THREAD

**Issue by ipsilantide** [RestComm/olympus#94]
@ipsilantide commented on [Fri Dec 23 2016](https://github.com/RestComm/graphics-design/issues/63)

What we've noticed is that the video of the participants who joining from mobile change the video area of the web browser .

**Comment by ipsilantide** [comment]
moved here from design repository

**Comment by marca56** [comment]
* discuss with @ipsilantide

**Comment by ammendonca** [comment]
This has already been fixed with previous commits, @ipsilantide reviewed and agrees.
