### ISSUE TITLE
Remove the yellow from text area

### ISSUE THREAD

**Issue by ipsilantide** [RestComm/olympus#95]
@ipsilantide commented on [Tue Feb 21 2017](https://github.com/RestComm/Restcomm-Connect/issues/1871)

@ipsilantide commented on [Thu Dec 22 2016](https://github.com/RestComm/graphics-design/issues/51)

Remove yellow or blue from the text areas 

---

@ipsilantide commented on [Tue Feb 21 2017](https://github.com/RestComm/Restcomm-Connect/issues/1871#issuecomment-281319094)

moved here from design repository

**Comment by ammendonca** [comment]
The yellow background is added by Chrome when auto-filling. We should decide if we want/should override that (users would be used to see yellow background for auto-filled forms).
