### ISSUE TITLE
Need to fix the size of the videos

### ISSUE THREAD

**Issue by ipsilantide** [RestComm/olympus#96]
@ipsilantide commented on [Tue Dec 20 2016](https://github.com/RestComm/graphics-design/issues/49)

We need to have less width and more height to the users video. As the page adjusted to wide screens the main video become very ''shallow'' ( you can see just the hair of the other participant ). We need to select carefully the size and the spaces  of the participants (smaller) videos. Need to find the balance

**Comment by ammendonca** [comment]
This was partially fixed by properly supporting portrait and landscape type of videos (previously the idea was to make the whole area occupied). It will still need some work on how to deal with the "remaining" area around a portrait mode video, as it looks a bit lost in the UI.
