### ISSUE TITLE
Audio and video answer on a call need to be more intuitive

### ISSUE THREAD

**Issue by ipsilantide** [RestComm/olympus#97]
@ipsilantide commented on [Mon Dec 19 2016](https://github.com/RestComm/graphics-design/issues/48)

At this time the experience of the user is not good since he is not able to see very clearly audio or video answer. Need to be redesigned to be more intuitive.

**Comment by ipsilantide** [comment]
moved here from design repository

**Comment by ammendonca** [comment]
Adding textual information so that it becomes clearer.

![image](https://cloud.githubusercontent.com/assets/1737954/26795506/d0e7c48c-4a1d-11e7-960d-93c3877a4ae3.png)
